_target_: primal.models.motionclip.MotionCLIP
cfg:
  network: 
    h_dim: 256
    n_layer: 4
    n_head: 8
    dropout: 0.1
    

  # motion representation
  canonical_tidx: start
  motion_repr: smplx_jts_locs_velocity_rotcont

  # text 
  n_vocab: 5


  # training
  lr: 1e-4
  lr_decay_rate: 1
  lr_warmup_steps: 0
  max_epochs: ${trainer.max_epochs}

  # data
  data: ${...data}

