_target_: lightning.Trainer

default_root_dir: ${hydra:runtime.output_dir}
min_epochs: 1
max_epochs: 30000
accelerator: cuda
devices: 1
check_val_every_n_epoch: 100
log_every_n_steps: 100
num_sanity_val_steps: 0
deterministic: False
strategy: ddp
accumulate_grad_batches: 1
enable_progress_bar: true